# Generated by Django 5.1.3 on 2024-12-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_alter_userfiles_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfiles",
            name="file_name",
            field=models.CharField(
                default="data.xlsx", max_length=100, verbose_name="نام فایل"
            ),
            preserve_default=False,
        ),
    ]
