# Generated by Django 5.1.3 on 2024-12-19 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_userfiles_file_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfiles",
            options={
                "verbose_name": "فایل کاربر",
                "verbose_name_plural": "فایل های کاربران",
            },
        ),
        migrations.AlterField(
            model_name="userfiles",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
